apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kafka-map-data
  labels:
    app: kafka
    component: map
spec:
  storageClassName: ceph-block
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: kafka
  labels:
    app: kafka
    component: server
spec:
  ports:
  - port: 9092
    name: broker
    targetPort: 9092
  - port: 9093
    name: controller
    targetPort: 9093
  - port: 9094
    name: external
  selector:
    app: kafka
    component: server
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-map
  labels:
    app: kafka
    component: server
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: kafka
    component: map
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka
  labels:
    app: kafka
    component: server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka
      component: server
  template:
    metadata:
      labels:
        app: kafka
        component: server
    spec:
      containers:
      - name: kafka-server
        image: bitnami/kafka:3.2.3
        resources:
          limits:
            cpu: 1
            memory: 2Gi
        env:
        - name: KAFKA_CFG_NODE_ID
          value: "0"
        - name: KAFKA_CFG_PROCESS_ROLES
          value: "controller,broker"
        - name: KAFKA_CFG_LISTENERS
          value: "PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094"
        - name: KAFKA_CFG_ADVERTISED_LISTENERS
          value: "PLAINTEXT://:9092,EXTERNAL://kafka.kafka:9094"
        - name: KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP
          value: "CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT"
        - name: KAFKA_CFG_CONTROLLER_QUORUM_VOTERS
          value: "0@127.0.0.1:9093"
        - name: KAFKA_CFG_CONTROLLER_LISTENER_NAMES
          value: "CONTROLLER"
        ports:
        - containerPort: 9092
          name: broker
        - containerPort: 9094
          name: external
        - containerPort: 9093
          name: controller
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-map
  labels:
    app: kafka
    component: map
spec:
  replicas: 0
  selector:
    matchLabels:
      app: kafka
      component: map
  template:
    metadata:
      labels:
        app: kafka
        component: map
    spec:
      containers:
      - name: kafka-map
        image: dushixiang/kafka-map:v1.3.3
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
        env:
        - name: DEFAULT_USERNAME
          value: admin
        - name: DEFAULT_PASSWORD
          value: admin
        ports:
        - containerPort: 8080
          name: kafka-map
        volumeMounts:
        - name: data
          mountPath: /usr/local/kafka-map/data
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: kafka-map-data
