apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: clickhouse-data
  labels:
    app: clickhouse
spec:
  storageClassName: ceph-block
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 80Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: clickhouse-log
  labels:
    app: clickhouse
spec:
  storageClassName: ceph-block
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: clickhouse
  labels:
    app: clickhouse
spec:
  type: NodePort
  ports:
  - port: 8123
    name: http
    targetPort: 8123
    nodePort: 30012
  - port: 9000
    name: tcp
    targetPort: 9000
    nodePort: 30013
  selector:
    app: clickhouse
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: clickhouse
  labels:
    app: clickhouse
spec:
  replicas: 1
  selector:
    matchLabels:
      app: clickhouse
  template:
    metadata:
      labels:
        app: clickhouse
    spec:
      containers:
      - name: clickhouse
        image: clickhouse/clickhouse-server:23.8
        resources:
          limits:
            cpu: 1
            memory: 4Gi
        env:
        - name: CLICKHOUSE_USER
          value: admin
        - name: CLICKHOUSE_PASSWORD
          value: password
        - name: CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT
          value: "1"
        ports:
        - containerPort: 8123
          name: http
        - containerPort: 9000
          name: tcp
        volumeMounts:
        - name: data
          mountPath: /var/lib/clickhouse
        - name: log
          mountPath: /var/log/clickhouse-server
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: clickhouse-data
      - name: log
        persistentVolumeClaim:
          claimName: clickhouse-log
