apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: stor-share
  labels:
    app: stor-share
spec:
  storageClassName: ceph-filesystem
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 150Gi
