apiVersion: v1
kind: Service
metadata:
  name: flink-jobmanager-nodeport
  labels:
    app: flink-standalone-cluster
    component: jobmanager
spec:
  type: NodePort
  ports:
  - port: 8081
    targetPort: 8081
    nodePort: 30002
  selector:
    app: flink-standalone-cluster
    component: jobmanager
    type: flink-standalone-kubernetes
